name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.2]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Test
      env:
        MONGO_URI: "mongodb://localhost:27017"
      run: go test -v -coverpkg ./... ./test -coverprofile profile.cov
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        flag-name: Go-${{ matrix.go }}
        parallel: true
    
    - uses: shogo82148/actions-goveralls@v1
      with:
        parallel-finished: true
